export interface ManifestOptions {
  appId: string
  name: string
  appType?: 'FlipperAppType.EXTERNAL' | 'FlipperAppType.APP' | 'FlipperAppType.PLUGIN'
  icon?: string
  entryPoint?: string
  version?: string
  stackSize?: number
  category?: string
  description?: string
  author?: string
}

export function buildManifest(opts: ManifestOptions): string {
  const {
    appId,
    name,
    appType = 'FlipperAppType.EXTERNAL',
    icon = '',
  entryPoint = `app_main`,
    version = '0.1.0',
    stackSize = 4 * 1024,
    category = 'General',
    description = 'Generated by Kiisu Blocks',
    author = 'Unknown',
  } = opts

  const lines: string[] = []
  lines.push('App(')
  lines.push(`    appid="${appId}",`)
  lines.push(`    name="${name}",`)
  lines.push(`    apptype=${appType},`)
  lines.push(`    entry_point="${entryPoint}",`)
  lines.push(`    stack_size=${stackSize},`)
  if (icon) lines.push(`    fap_icon="${icon}",`)
  lines.push(`    fap_category="${category}",`)
  lines.push(`    fap_description="${description}",`)
  lines.push(`    fap_author="${author}",`)
  lines.push(`    fap_version="${version}",`)
  lines.push(')')
  return lines.join('\n') + '\n'
}
